-- Crear tablas
CREATE TABLE IF NOT EXISTS winners (
  device_id VARCHAR(100) PRIMARY KEY,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS prize_tokens (
  id INT AUTO_INCREMENT PRIMARY KEY,
  claimed_by VARCHAR(100) NULL,
  claimed_at TIMESTAMP NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Sembrar 10 tokens si la tabla está vacía
INSERT INTO prize_tokens (claimed_by, claimed_at)
SELECT NULL, NULL FROM dual
UNION ALL SELECT NULL, NULL
UNION ALL SELECT NULL, NULL
UNION ALL SELECT NULL, NULL
UNION ALL SELECT NULL, NULL
UNION ALL SELECT NULL, NULL
UNION ALL SELECT NULL, NULL
UNION ALL SELECT NULL, NULL
UNION ALL SELECT NULL, NULL
UNION ALL SELECT NULL, NULL
WHERE (SELECT COUNT(*) FROM prize_tokens) = 0;
